name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup and Test
        uses: ./github/actions/setup-and-test
        with:
          node-version: 16
          test-command: npm test